### ISSUE TITLE
S3Client error java.lang.NoClassDefFoundError: kotlin/coroutines/jvm/internal/SpillingKt with 1.5.0+

### ISSUE THREAD

**Issue by afranken** [awslabs/aws-sdk-kotlin#1654]
### Describe the bug

We have a test
https://github.com/adobe/S3Mock/blob/main/integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/KotlinSDKIT.kt#L36

That works just fine with aws-sdk-kotlin 1.4.125
When updating to 1.5.0, we see an error:

```
[ERROR] com.adobe.testing.s3mock.its.KotlinSDKIT.createAndDeleteBucket(TestInfo) -- Time elapsed: 0.032 s <<< ERROR!
java.lang.NoClassDefFoundError: kotlin/coroutines/jvm/internal/SpillingKt
        at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.execute(SdkHttpOperation.kt:119)
        at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.roundTrip(SdkHttpOperation.kt:96)
        at aws.sdk.kotlin.services.s3.DefaultS3Client.createBucket(DefaultS3Client.kt:402)
        at com.adobe.testing.s3mock.its.KotlinSDKIT$createAndDeleteBucket$1.invokeSuspend(KotlinSDKIT.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at com.adobe.testing.s3mock.its.KotlinSDKIT.createAndDeleteBucket(KotlinSDKIT.kt:36)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: kotlin.coroutines.jvm.internal.SpillingKt
        ... 16 more
```

Not sure where this class is supposed to come from, it does not seem to be part of the Kotlin Coroutines library.

Simple code like

```
S3Client.fromEnvironment { region = "us-east-2" }.use {
      it.listBuckets()
    }
```
Throws the same error in our setup.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected behavior

The code should run without an exception.

### Current behavior

See description

### Steps to Reproduce

Clone https://github.com/adobe/S3Mock
Update aws-sdk-kotlin version to 1.5.0+ in the main pom.xml
run `make` (starts a maven build, Docker is needed.)

Just running the test will throw the same error.
https://github.com/adobe/S3Mock/blob/main/integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/KotlinSDKIT.kt#L36

### AWS SDK for Kotlin version

1.5.3

### Platform (JVM/JS/Native)

JVM

### Operating system and version

MacOS 15.5

**Comment by lauzadis** [comment]
Relevant links
- https://github.com/JetBrains/kotlin/blob/master/compiler/backend/src/org/jetbrains/kotlin/codegen/coroutines/coroutines-codegen.md#spilled-variables-cleanup
- https://slack-chats.kotlinlang.org/t/28493258/the-testing-setup-in-https-github-com-demiurg906-kotlin-comp

**Comment by afranken** [comment]
forgot to add: Dependabot tries to update the version for us, the error is in the PR logs:
https://github.com/adobe/S3Mock/pull/2527

**Comment by ianbotsf** [comment]
Hi @afranken, I'm guessing that multiple versions of some transient dependency are in scope and Maven is resolving to one that does not support the latest version of Kotlin and the SDK. Can you dump your dependency tree to see what JARs are being used at runtime?

**Comment by afranken** [comment]
@ianbotsf thanks for looking into this.

with 1.4.125:

```
❯ mvn dependency:tree
Picked up _JAVA_OPTIONS:  -Djava.awt.headless=true
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -------------< com.adobe.testing:s3mock-integration-tests >-------------
[INFO] Building S3Mock - Integration Tests 4.7.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.adobe.testing:s3mock:jar:4.7.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.adobe.testing:s3mock-docker:pom:4.7.1-SNAPSHOT is missing, no dependency information available
[INFO] 
[INFO] --- dependency:3.8.1:tree (default-cli) @ s3mock-integration-tests ---
[INFO] com.adobe.testing:s3mock-integration-tests:jar:4.7.1-SNAPSHOT
[INFO] +- com.adobe.testing:s3mock:jar:4.7.1-SNAPSHOT:test
[INFO] +- com.adobe.testing:s3mock-docker:pom:4.7.1-SNAPSHOT:test
[INFO] +- org.assertj:assertj-core:jar:3.27.3:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.17.6:test
[INFO] +- org.awaitility:awaitility:jar:4.2.2:test
[INFO] |  \- org.hamcrest:hamcrest:jar:3.0:test
[INFO] +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:2.2.0:test
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.25:test
[INFO] |  |  \- org.jetbrains:annotations:jar:13.0:test
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.25:test
[INFO] +- org.jetbrains.kotlin:kotlin-test-junit:jar:2.2.0:test
[INFO] |  +- org.jetbrains.kotlin:kotlin-test:jar:2.2.0:test
[INFO] |  \- junit:junit:jar:4.13.2:test
[INFO] |     \- org.hamcrest:hamcrest-core:jar:3.0:test
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.12.2:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.12.2:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.12.2:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.12.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-params:jar:5.12.2:test
[INFO] +- org.mockito.kotlin:mockito-kotlin:jar:6.0.0:test
[INFO] |  +- org.mockito:mockito-core:jar:5.17.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.17.6:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.3:test
[INFO] |  \- org.jetbrains.kotlin:kotlin-reflect:jar:1.9.25:test
[INFO] +- software.amazon.awssdk:aws-query-protocol:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:protocol-core:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:aws-core:jar:2.32.7:test
[INFO] |  |  +- software.amazon.awssdk:retries:jar:2.32.7:test
[INFO] |  |  \- software.amazon.eventstream:eventstream:jar:1.0.1:test
[INFO] |  +- software.amazon.awssdk:sdk-core:jar:2.32.7:test
[INFO] |  |  +- org.slf4j:slf4j-api:jar:2.0.17:test
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:test
[INFO] |  +- software.amazon.awssdk:annotations:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-client-spi:jar:2.32.7:test
[INFO] |  \- software.amazon.awssdk:utils:jar:2.32.7:test
[INFO] +- software.amazon.awssdk:aws-xml-protocol:jar:2.32.7:test
[INFO] +- software.amazon.awssdk:s3:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:arns:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:profiles:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:crt-core:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-auth:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:identity-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-auth-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-auth-aws:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:checksums:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:checksums-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:retries-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:auth:jar:2.32.7:test
[INFO] |  |  \- software.amazon.awssdk:http-auth-aws-eventstream:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:regions:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:metrics-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:json-utils:jar:2.32.7:test
[INFO] |  |  \- software.amazon.awssdk:third-party-jackson-core:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:endpoints-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:apache-client:jar:2.32.7:test
[INFO] |  \- software.amazon.awssdk:netty-nio-client:jar:2.32.7:test
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-codec:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-transport:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-common:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-buffer:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-handler:jar:4.1.123.Final:test
[INFO] |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-transport-classes-epoll:jar:4.1.123.Final:test
[INFO] |     \- io.netty:netty-resolver:jar:4.1.123.Final:test
[INFO] +- software.amazon.awssdk:url-connection-client:jar:2.32.7:test
[INFO] +- software.amazon.awssdk:aws-crt-client:jar:2.32.7:test
[INFO] |  \- software.amazon.awssdk.crt:aws-crt:jar:0.38.1:test
[INFO] +- software.amazon.awssdk:s3-transfer-manager:jar:2.32.7:test
[INFO] +- aws.sdk.kotlin:s3-jvm:jar:1.4.125:test
[INFO] |  +- aws.sdk.kotlin:aws-config-jvm:jar:1.4.125:test
[INFO] |  |  +- aws.smithy.kotlin:serde-json-jvm:jar:1.4.23:test
[INFO] |  |  +- aws.smithy.kotlin:serde-form-url-jvm:jar:1.4.23:test
[INFO] |  |  +- aws.smithy.kotlin:aws-json-protocols-jvm:jar:1.4.23:test
[INFO] |  |  \- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.8.1:test
[INFO] |  +- aws.sdk.kotlin:aws-core-jvm:jar:1.4.125:test
[INFO] |  +- aws.sdk.kotlin:aws-endpoint-jvm:jar:1.4.125:test
[INFO] |  +- aws.smithy.kotlin:http-client-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:runtime-core-jvm:jar:1.4.23:test
[INFO] |  |  \- com.squareup.okio:okio-jvm:jar:3.9.1:test
[INFO] |  +- aws.smithy.kotlin:smithy-client-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:telemetry-api-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:aws-credentials-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:aws-event-stream-jvm:jar:1.4.23:test
[INFO] |  +- aws.sdk.kotlin:aws-http-jvm:jar:1.4.125:test
[INFO] |  +- aws.smithy.kotlin:aws-protocol-core-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:aws-signing-common-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:aws-signing-default-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:aws-xml-protocols-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:http-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:http-auth-jvm:jar:1.4.23:test
[INFO] |  |  \- aws.smithy.kotlin:http-auth-api-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:http-auth-aws-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:http-client-engine-default-jvm:jar:1.4.23:test
[INFO] |  |  \- aws.smithy.kotlin:http-client-engine-okhttp-jvm:jar:1.4.23:test
[INFO] |  |     +- com.squareup.okhttp3:okhttp:jar:5.0.0-alpha.14:test
[INFO] |  |     \- com.squareup.okhttp3:okhttp-coroutines:jar:5.0.0-alpha.14:test
[INFO] |  +- aws.smithy.kotlin:identity-api-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:serde-jvm:jar:1.4.23:test
[INFO] |  +- aws.smithy.kotlin:serde-xml-jvm:jar:1.4.23:test
[INFO] |  \- aws.smithy.kotlin:telemetry-defaults-jvm:jar:1.4.23:test
[INFO] |     \- aws.smithy.kotlin:logging-slf4j2-jvm:jar:1.4.23:test
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.14:test
[INFO] |  +- commons-logging:commons-logging:jar:1.2:test
[INFO] |  \- commons-codec:commons-codec:jar:1.18.0:test
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.4.16:test
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.5.14:test
[INFO] \- tel.schich:aws-s3-post-object-presigner:jar:0.1.1:test
[INFO]    \- com.google.code.gson:gson:jar:2.13.1:test
[INFO]       \- com.google.errorprone:error_prone_annotations:jar:2.38.0:test
```

with 1.5.10:

```
❯ mvn dependency:tree               
Picked up _JAVA_OPTIONS:  -Djava.awt.headless=true
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] -------------< com.adobe.testing:s3mock-integration-tests >-------------
[INFO] Building S3Mock - Integration Tests 4.7.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.adobe.testing:s3mock:jar:4.7.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.adobe.testing:s3mock-docker:pom:4.7.1-SNAPSHOT is missing, no dependency information available
[INFO] 
[INFO] --- dependency:3.8.1:tree (default-cli) @ s3mock-integration-tests ---
[INFO] com.adobe.testing:s3mock-integration-tests:jar:4.7.1-SNAPSHOT
[INFO] +- com.adobe.testing:s3mock:jar:4.7.1-SNAPSHOT:test
[INFO] +- com.adobe.testing:s3mock-docker:pom:4.7.1-SNAPSHOT:test
[INFO] +- org.assertj:assertj-core:jar:3.27.3:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.17.6:test
[INFO] +- org.awaitility:awaitility:jar:4.2.2:test
[INFO] |  \- org.hamcrest:hamcrest:jar:3.0:test
[INFO] +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:2.2.0:test
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.25:test
[INFO] |  |  \- org.jetbrains:annotations:jar:13.0:test
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.25:test
[INFO] +- org.jetbrains.kotlin:kotlin-test-junit:jar:2.2.0:test
[INFO] |  +- org.jetbrains.kotlin:kotlin-test:jar:2.2.0:test
[INFO] |  \- junit:junit:jar:4.13.2:test
[INFO] |     \- org.hamcrest:hamcrest-core:jar:3.0:test
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.12.2:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.12.2:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.12.2:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.12.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-params:jar:5.12.2:test
[INFO] +- org.mockito.kotlin:mockito-kotlin:jar:6.0.0:test
[INFO] |  +- org.mockito:mockito-core:jar:5.17.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.17.6:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.3:test
[INFO] |  \- org.jetbrains.kotlin:kotlin-reflect:jar:1.9.25:test
[INFO] +- software.amazon.awssdk:aws-query-protocol:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:protocol-core:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:aws-core:jar:2.32.7:test
[INFO] |  |  +- software.amazon.awssdk:retries:jar:2.32.7:test
[INFO] |  |  \- software.amazon.eventstream:eventstream:jar:1.0.1:test
[INFO] |  +- software.amazon.awssdk:sdk-core:jar:2.32.7:test
[INFO] |  |  +- org.slf4j:slf4j-api:jar:2.0.17:test
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:test
[INFO] |  +- software.amazon.awssdk:annotations:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-client-spi:jar:2.32.7:test
[INFO] |  \- software.amazon.awssdk:utils:jar:2.32.7:test
[INFO] +- software.amazon.awssdk:aws-xml-protocol:jar:2.32.7:test
[INFO] +- software.amazon.awssdk:s3:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:arns:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:profiles:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:crt-core:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-auth:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:identity-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-auth-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:http-auth-aws:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:checksums:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:checksums-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:retries-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:auth:jar:2.32.7:test
[INFO] |  |  \- software.amazon.awssdk:http-auth-aws-eventstream:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:regions:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:metrics-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:json-utils:jar:2.32.7:test
[INFO] |  |  \- software.amazon.awssdk:third-party-jackson-core:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:endpoints-spi:jar:2.32.7:test
[INFO] |  +- software.amazon.awssdk:apache-client:jar:2.32.7:test
[INFO] |  \- software.amazon.awssdk:netty-nio-client:jar:2.32.7:test
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-codec:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-transport:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-common:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-buffer:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-handler:jar:4.1.123.Final:test
[INFO] |     |  \- io.netty:netty-transport-native-unix-common:jar:4.1.123.Final:test
[INFO] |     +- io.netty:netty-transport-classes-epoll:jar:4.1.123.Final:test
[INFO] |     \- io.netty:netty-resolver:jar:4.1.123.Final:test
[INFO] +- software.amazon.awssdk:url-connection-client:jar:2.32.7:test
[INFO] +- software.amazon.awssdk:aws-crt-client:jar:2.32.7:test
[INFO] |  \- software.amazon.awssdk.crt:aws-crt:jar:0.38.1:test
[INFO] +- software.amazon.awssdk:s3-transfer-manager:jar:2.32.7:test
[INFO] +- aws.sdk.kotlin:s3-jvm:jar:1.5.10:test
[INFO] |  +- aws.sdk.kotlin:aws-config-jvm:jar:1.5.10:test
[INFO] |  |  +- aws.smithy.kotlin:serde-json-jvm:jar:1.5.1:test
[INFO] |  |  +- aws.smithy.kotlin:serde-form-url-jvm:jar:1.5.1:test
[INFO] |  |  +- aws.smithy.kotlin:aws-json-protocols-jvm:jar:1.5.1:test
[INFO] |  |  \- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.8.1:test
[INFO] |  +- aws.sdk.kotlin:aws-core-jvm:jar:1.5.10:test
[INFO] |  +- aws.sdk.kotlin:aws-endpoint-jvm:jar:1.5.10:test
[INFO] |  +- aws.smithy.kotlin:http-client-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:runtime-core-jvm:jar:1.5.1:test
[INFO] |  |  \- com.squareup.okio:okio-jvm:jar:3.15.0:test
[INFO] |  +- aws.smithy.kotlin:smithy-client-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:telemetry-api-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:aws-credentials-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:aws-event-stream-jvm:jar:1.5.1:test
[INFO] |  +- aws.sdk.kotlin:aws-http-jvm:jar:1.5.10:test
[INFO] |  +- aws.smithy.kotlin:aws-protocol-core-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:aws-signing-common-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:aws-signing-default-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:aws-xml-protocols-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:http-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:http-auth-jvm:jar:1.5.1:test
[INFO] |  |  \- aws.smithy.kotlin:http-auth-api-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:http-auth-aws-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:http-client-engine-default-jvm:jar:1.5.1:test
[INFO] |  |  \- aws.smithy.kotlin:http-client-engine-okhttp-jvm:jar:1.5.1:test
[INFO] |  |     +- com.squareup.okhttp3:okhttp-jvm:jar:5.1.0:test
[INFO] |  |     \- com.squareup.okhttp3:okhttp-coroutines:jar:5.1.0:test
[INFO] |  +- aws.smithy.kotlin:identity-api-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:serde-jvm:jar:1.5.1:test
[INFO] |  +- aws.smithy.kotlin:serde-xml-jvm:jar:1.5.1:test
[INFO] |  \- aws.smithy.kotlin:telemetry-defaults-jvm:jar:1.5.1:test
[INFO] |     \- aws.smithy.kotlin:logging-slf4j2-jvm:jar:1.5.1:test
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.14:test
[INFO] |  +- commons-logging:commons-logging:jar:1.2:test
[INFO] |  \- commons-codec:commons-codec:jar:1.18.0:test
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.4.16:test
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.5.14:test
[INFO] \- tel.schich:aws-s3-post-object-presigner:jar:0.1.1:test
[INFO]    \- com.google.code.gson:gson:jar:2.13.1:test
[INFO]       \- com.google.errorprone:error_prone_annotations:jar:2.38.0:test
```

**Comment by ianbotsf** [comment]
Thanks for the dependency manifest. It looks like at least two dependencies are not in sync with Kotlin **2.2.0**:
* **org.jetbrains.kotlin:kotlin-stdlib**: current version is **1.9.25** but supported version is **2.2.0+**
* **org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm**: current version is **1.8.1** but supported version is **1.10.2+**

Can you try explicitly declaring the supported versions of those dependencies in your project?

**Comment by afranken** [comment]
@ianbotsf thanks, I had to force Maven to converge on the latest available dependency versions and declare Kotlin and coroutines dependencies directly to get this resolved.
